version: "3"

x-services:
  &service_default
  init: true
  restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  extra_hosts:
    - "etcd:172.20.0.2"
  networks:
    junonet:
  environment:
    TZ: America/Los_Angeles

services:
  etcd:
    <<: *service_default
    image: ghcr.io/paypal/junodb/junoclusterserv:${VERSION:-latest}
    container_name: etcd
    environment:
      CLIENT_PORT: "2379"
      DATA_DIR: .
      PEER_NAMES: "p0"
      PEER_PORT: "2378"
      INITIAL_CLUSTER: "172.20.0.2"
    expose:
      - "2379"
    healthcheck:
      test: "export ETCDCTL_API=3 && ./etcdctl endpoint health --cluster --endpoints=etcd:2379"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      junonet:
        ipv4_address: 172.20.0.2

  clustercfg:
    <<: *service_default
    image: ghcr.io/paypal/junodb/junoclustercfg:${VERSION:-latest}
    container_name: clustercfg
    command:
      [
        "./clustermgr",
        "--config",
        "/opt/juno/enabled_config.toml",
        "--cmd",
        "store",
        "--type",
        "cluster_info"
      ]
    environment:
      NUM_ZONES: "1"
      SS_HOSTS: '[["storageserv"]]'
    depends_on:
      etcd:
        condition: service_healthy
    healthcheck:
      test: "nc -vz etcd 2379"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  storageserv:
    <<: *service_default
    image: ghcr.io/paypal/junodb/junostorageserv:${VERSION:-latest}
    container_name: storageserv
    depends_on:
      clustercfg:
        condition: service_healthy
    healthcheck:
      test: "nc -vz 127.0.0.1 8089"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "${SS_ADMIN_PORT:-8089}:8089"
    volumes:
      - "storageserv_data:/opt/juno/data:rw"

  proxy:
    <<: *service_default
    image: ghcr.io/paypal/junodb/junoserv:${VERSION:-latest}
    container_name: proxy
    ports:
      - "${PROXY_ADMIN_PORT:-8088}:8088"
      - "${PROXY_TCP_PORT:-8080}:8080"
      - "${PROXY_TLS_PORT:-5080}:5080"
    healthcheck:
      test: "nc -vz 127.0.0.1 5080"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      - storageserv

  junoclient:
    <<: *service_default
    image: ghcr.io/paypal/junodb/junoclient:${VERSION:-latest}
    container_name: junoclient
    depends_on:
      - proxy
    healthcheck:
      test: "nc -vz proxy 5080"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

networks:
  junonet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  storageserv_data: {}
